# Generated by Django 4.1.5 on 2023-01-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('experience', models.IntegerField(null=True)),
                ('biography', models.TextField(null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('fk_hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='task_one.hospital')),
            ],
        ),
    ]
