# Generated by Django 4.1.5 on 2023-01-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_one', '0003_alter_doctors_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='education',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
