# Generated by Django 3.2.16 on 2023-01-09 18:05

from django.db import migrations, models
import imageapp.fields
import imageapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', imageapp.fields.WEBPField(height_field='height', upload_to=imageapp.models.image_folder, verbose_name='Image', width_field='width')),
            ],
        ),
    ]
