# Generated by Django 3.2.16 on 2023-01-09 18:15

from django.db import migrations
import imageapp.fields
import imageapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imageapp.fields.WEBPField(upload_to=imageapp.models.image_folder, verbose_name='Image'),
        ),
    ]
