# Generated by Django 4.1.5 on 2023-01-10 04:32

from django.db import migrations
import imageapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imageapp.fields.WEBPField(upload_to='photos', verbose_name='Image'),
        ),
    ]
