# Generated by Django 4.1.5 on 2023-01-10 05:45

from django.db import migrations
import imageapp.fields
import imageapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imageapp.fields.WEBPField(upload_to=imageapp.models.image_folder, verbose_name='Image'),
        ),
    ]
